package org.snomed.entities;

public enum Refset {
    ASSOCIATION_REFERENCE,
    DESCRIPTOR,
    SIMPLE,
    SIMPLE_MAP,
    EXTENDED_MAP,
    MRCM_MODULE_SCOPE,
    MRCM_DOMAIN,
    MRCM_ATTRIBUTE_DOMAIN,
    MRCM_ATTRIBUTE_RANGE,
    MODULE_DEPENDENCY,
    LANGUAGE,
    DESCRIPTION_TYPE,
    ATTRIBUTE_VALUE
}
